#! /usr/bin/env bash
#
# Remove unstable pieces in Zeek logs.

sed -E 's/^ *#(open|close).(19|20)..-..-..-..-..-..$/#\1 XXXX-XX-XX-XX-XX-XX/g' |
    $ZEEK_BTEST/scripts/diff-sort |
    $ZEEK_BTEST/scripts/diff-remove-timestamps |
    $ZEEK_BTEST/scripts/diff-remove-abspath
